[package]
name = "core_ui"
version = "0.0.1"
edition = "2021"

[dependencies]
sport_core = { path = "../sport_core" }
sport_core_db = { path = "../sport_core_db" }
log = "0.4"
thiserror = "1.0"
tui = "0.19"
crossterm = "0.25"
